### ISSUE TITLE
Swift 3.1

### ISSUE THREAD

**Issue by kafermeister** [LogmeinRescue/iOS-SDK#15]
Hi,

Attempting to integrate this into our Swift 3.1 enterprise app for evaluation prior to purchase, and I'm hitting the following compile error:

/Users/pjr/Documents/Development/iOS/WebWrapper/WebWrapper/AppDelegate.swift:12:8: Module compiled with Swift 3.0.2 cannot be imported in Swift 3.1: /Users/pjr/Documents/Development/iOS/WebWrapper/Pods/RescueSDK/Frameworks/RescueCore.framework/Modules/RescueCore.swiftmodule/arm.swiftmodule

Will you be providing Swift 3.1 frameworks?

Thanks
Peter

**Comment by bbanyai** [comment]
Hello,
 
We’re aware of the issue, and it is being actively worked on. We’ll get back to you as soon as we have a new release, that solves this.
 
Thank you very much for your feedback

**Comment by balazsbanyai** [comment]
Hello, 

Please use our latest release: https://github.com/LogmeinRescue/iOS-SDK/releases/tag/2.2.2
This should be compatible with the latest tools.

Thanks
