### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by kafermeister** [LogmeinRescue/iOS-SDK#18]
Hi,

Just thought I'd open a ticket for swift 4 support.  Currently our swift 4 project (even though the Cocoapods is set to use Swift 3.2, but I guess it's something to do with it being a pre-compiled library), throws the following error:

ld: /Users/pjr/Documents/Development/iOS/WebWrapper/Pods/RescueSDK/Frameworks/RescueCameraStreaming.framework/RescueCameraStreaming compiled with older version of Swift language (3.0) than previous files (4.0) file '/Users/pjr/Documents/Development/iOS/WebWrapper/Pods/RescueSDK/Frameworks/RescueCameraStreaming.framework/RescueCameraStreaming' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks
Peter

**Comment by balazsbanyai** [comment]
Hello, 

Thanks for the feedback. We are working on the solution. We will get back to you, as soon as we have the new version of the SDK that supports swift 4.

Thank you very much for your feedback

**Comment by balazsbanyai** [comment]
Hello,

Please use our latest release. (3.1.1)
This should be compatible with the latest tools.

Thanks
