### ISSUE TITLE
Compatibility with Xcode 9.3 / Swift 4.1

### ISSUE THREAD

**Issue by tomlongo** [LogmeinRescue/iOS-SDK#21]
It seems I cannot compile my project with the SDK currently without getting an error

`Module compiled with Swift 4.0.2 cannot be imported in Swift 4.1: [...] RescueCore.swiftmodule/x86_64.swiftmodule`

I have installed a toolchain to roll back to Swift 4.0.2, which allows me to build, but crashes on launch with the error:

`Incompatible library version: RescueCore requires version 1.0.0 or later, but libswiftAVFoundation.dylib provides version 0.0.0`

Is there a way to get it to run on Xcode 9.3/Swift 4.1 currently?

**Comment by meddle447** [comment]
Same here. It would be nice if they anticipated releases that are not compatible and updated quicker.

**Comment by tibiur** [comment]
We are working on a new release with Xcode 9.3 and Swift 4.1.  Thank you for your patience.

**Comment by tomlongo** [comment]
Hello, thanks for updating this, though it appears with the release of Xcode 10 and Swift 4.2 it does not compile again. Is it possible to get it fixed again for the newest versions?

**Comment by tibiur** [comment]
Hello, we plan to release a new version later this month.
