### ISSUE TITLE
Warning in project using RescueBroadcast

### ISSUE THREAD

**Issue by KiranKumar36** [LogmeinRescue/iOS-SDK#27]
**Environment**
Xcode 10.1
Swift 4.2
iPhone 7 plus
iOS 12.1.3

**Description**
Xcode shows warning about dylib

> Linking against a dylib which is not safe for use in application extensions

<img width="1137" alt="screenshot 2019-02-15 at 10 51 09 am" src="https://user-images.githubusercontent.com/29379567/52836473-a5a80300-3110-11e9-8788-f5767af649ce.png">

**Comment by tibiur** [comment]
We have some unused unsafe API linked in the broadcast extension framework. We are planning to refactor it. We are using the SDK this way for over a year and there was no problem submitting to the app store.
