### ISSUE TITLE
Error in updating pod RescueSDK/Broadcast (= 4.0.1)

### ISSUE THREAD

**Issue by KiranKumar36** [LogmeinRescue/iOS-SDK#29]
**Enviroment**
Xcode 10.1
Swift 4.2
iPhone 7 plus
iOS 12.1.3
Minimum Deployment target for current app **10.0**

**Description**

Pod install says there is issue in updating RescueSDK/Broadcast w.r.t minimum deployment target  

**Error**

[!] CocoaPods could not find compatible versions for pod "RescueSDK/Broadcast":
  In Podfile:
    RescueSDK/Broadcast (= 4.0.1)

Specs satisfying the `RescueSDK/Broadcast (= 4.0.1)` dependency were found, but they required a higher minimum deployment target.

<img width="572" alt="screenshot 2019-03-05 at 11 31 41 am" src="https://user-images.githubusercontent.com/29379567/53786031-53ecde80-3f40-11e9-9fd3-c73a4b8fbd91.png">

**Comment by MintBerryCrunch** [comment]
Same

**Comment by tibiur** [comment]
What is the deployment target for your broadcast extension? it should be minimum 11.0

**Comment by KiranKumar36** [comment]
Okay so it mean extension should be minimum 11.0. Thank you
