### ISSUE TITLE
Session callbacks for Broadcast session 

### ISSUE THREAD

**Issue by KiranKumar36** [LogmeinRescue/iOS-SDK#30]
**Environment**
Xcode 10.1
Swift 4.2
iPhone 7 plus
iOS 12.1.3

**Description**

Not getting callbacks when the session status changed in the following scenarios.

1.  When LMI agent pause, resume and close the session in LMI console
2.  When a user starts/stops the session from the broadcast picker

We get only callbacks for session ready and endSession trigger by the client.

The same has been verified with latest SDK (4.0.1) but still issue persists.

**Comment by tibiur** [comment]
We are working on a swift 5 release and investigating this issue.

**Comment by tibiur** [comment]
The app or the extension is not getting the session status changes? If you use the broadcast picker to start your extension the app won't get any status changes, only the extension should.

**Comment by KiranKumar36** [comment]
@tibiur Do we not get status update in app "rescueSessionStatusDidChange"?

**Comment by KiranKumar36** [comment]
@tibiur Any update on the session status passing to host app?

**Comment by tibiur** [comment]
In  our apps we use Darwin notifications for inter process communication. (CFNotificationCenter functions)
