### ISSUE TITLE
Compatibility with Xcode 10.2 / Swift 5

### ISSUE THREAD

**Issue by KiranKumar36** [LogmeinRescue/iOS-SDK#32]
Xcode 10.2 and Swift 5 came out. We started working on migrating our code ASAP, but we can't build our app because you're shipping a binary Swift framework. 
swiftc doesn't support importing modules built with earlier version of compiler, which leads to build failures like below:

`Module compiled with Swift 4.2 cannot be imported in Swift 5: [...] RescueCore.swiftmodule/x86_64.swiftmodule`

It would be great if you could provide versions of your "current" SDK built with the new compiler, so we would be unblocked from working on our own migrations.

Thanks in advance!

**Comment by tibiur** [comment]
Hi!

We are working on the compatibility release.

**Comment by tibiur** [comment]
Hi!

Please check out the new release with swift 5.0!
