### ISSUE TITLE
Sample Broadcast(RescueBroadcastExampleExternal) app crashes on launch

### ISSUE THREAD

**Issue by KiranKumar36** [LogmeinRescue/iOS-SDK#34]
**Environment**
Xcode 10.2
Swift 5.0
iPhone SE
iOS 12.2

**Description**
Broadcast sample crashes in using **broadcastPicker.preferredExtension**

> RescueBroadcastExample[5702:652784] -[UIView setPreferredExtension:]: unrecognized selector sent to instance 0x105410a70
> 
> RescueBroadcastExample[5702:652784] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setPreferredExtension:]: unrecognized selector sent to instance 0x105410a70

**Comment by tibiur** [comment]
That is a strange bug. 
broadcastPicker is a RPSystemBroadcastPickerView and should have that method. 
You can just simply remove that line or add a print line before it, it looks like it works after that: print("\(broadcastPicker)")

**Comment by KiranKumar36** [comment]
@tibiur one more issue here is RPSystemBroadcastPickerView is not shown even after session is ready

**Comment by KiranKumar36** [comment]
This is working. so this issue can be closed
