### ISSUE TITLE
Camera Streaming stopped working

### ISSUE THREAD

**Issue by KiranKumar36** [LogmeinRescue/iOS-SDK#35]
**Environment**
Xcode 10.2
Swift 5
iPhone 7
iOS 12.2

**Description**
Camera streaming is not working after session gets connected and session status is active in console.

Tested the same in sample apps which include Swift 4.2 and swift 5 sdk. In both of them Issue persists.
This used to work before.

**Comment by KiranKumar36** [comment]
Queue Event log for the same

> [2019-05-02 1:23:54 PM] === Console started (7.12.3332 64-bit) ===
> [2019-05-02 1:23:54 PM] Host site: secure.logmeinrescue.com
> [2019-05-02 1:23:59 PM] Console configuration has been retrieved
> [2019-05-02 1:24:10 PM] Console ready
> [2019-05-02 1:24:17 PM] Chat log has been retrieved
> [2019-05-02 1:24:33 PM] Ending session 690103715...
> [2019-05-02 1:24:34 PM] Session 690103715 has been closed
> [2019-05-02 1:24:39 PM] Generating PIN Code...
> [2019-05-02 1:24:39 PM] Private code 327503 has been generated
> [2019-05-02 1:25:06 PM] Starting session 690107109...
> [2019-05-02 1:25:07 PM] Session 690107109 has been picked up
> [2019-05-02 1:25:07 PM] Session 690107109 ready
> [2019-05-02 1:26:04 PM] Ending session 690107109...
> [2019-05-02 1:26:04 PM] Session 690107109 has been closed
> [2019-05-02 1:26:08 PM] Generating PIN Code...
> [2019-05-02 1:26:08 PM] Private code 914361 has been generated
> [2019-05-02 1:27:24 PM] Starting session 690107316...
> [2019-05-02 1:27:24 PM] Session 690107316 has been picked up
> [2019-05-02 1:27:24 PM] Session 690107316 ready
> [2019-05-02 1:31:05 PM] Ending session 690107316...
> [2019-05-02 1:31:06 PM] Session 690107316 has been closed
> [2019-05-02 1:31:10 PM] Generating PIN Code...
> [2019-05-02 1:31:10 PM] Private code 380775 has been generated
> [2019-05-02 1:31:53 PM] Starting session 690107802...
> [2019-05-02 1:31:54 PM] Session 690107802 has been picked up
> [2019-05-02 1:31:54 PM] Session 690107802 ready
> [2019-05-02 1:37:31 PM] Ending session 690107802...
> [2019-05-02 1:37:31 PM] Session 690107802 has been closed
> [2019-05-02 1:37:43 PM] Generating PIN Code...
> [2019-05-02 1:37:43 PM] Private code 716426 has been generated
> [2019-05-02 1:38:16 PM] Starting session 690108580...
> [2019-05-02 1:38:17 PM] Session 690108580 has been picked up
> [2019-05-02 1:38:17 PM] Session 690108580 ready
> [2019-05-02 1:40:28 PM] Ending session 690108580...
> [2019-05-02 1:40:29 PM] Session 690108580 has been closed
> [2019-05-02 1:40:34 PM] Generating PIN Code...
> [2019-05-02 1:40:34 PM] Private code 637141 has been generated
> [2019-05-02 1:41:03 PM] Starting session 690108922...
> [2019-05-02 1:41:04 PM] Session 690108922 has been picked up
> [2019-05-02 1:41:04 PM] Session 690108922 ready
> [2019-05-02 1:45:04 PM] Ending session 690108922...
> [2019-05-02 1:45:05 PM] Session 690108922 has been closed
> [2019-05-02 1:45:11 PM] Generating PIN Code...
> [2019-05-02 1:45:11 PM] Private code 142193 has been generated
> [2019-05-02 1:46:05 PM] Generating PIN Code...
> [2019-05-02 1:46:06 PM] Private code 108481 has been generated
> [2019-05-02 1:46:27 PM] Starting session 690109526...
> [2019-05-02 1:46:28 PM] Session 690109526 has been picked up
> [2019-05-02 1:46:28 PM] Session 690109526 ready
> [2019-05-02 1:50:15 PM] Your status is away
> [2019-05-02 1:51:35 PM] Ending session 690109526...
> 
> [2019-05-02 2:46:13 PM] === Console started (7.12.3332 64-bit) ===
> [2019-05-02 2:46:13 PM] Host site: secure.logmeinrescue.com
> [2019-05-02 2:47:38 PM] Console configuration has been retrieved
> [2019-05-02 2:47:45 PM] Console ready
> [2019-05-02 2:47:59 PM] Generating PIN Code...
> [2019-05-02 2:47:59 PM] Private code 475769 has been generated
> [2019-05-02 2:48:25 PM] Starting session 690116844...
> [2019-05-02 2:48:26 PM] Session 690116844 has been picked up
> [2019-05-02 2:48:26 PM] Session 690116844 ready

**Comment by kunaldas103** [comment]
Same issue is happening to me as well, it used to work perfectly before, all of a sudden it stopped working, so kindly look into this.

**Comment by avpn989** [comment]
I am also facing the same issue, camera streaming is not working.
**Environment**
Xcode 10.2
Swift 5
iPhone 7
iOS 12.2

**Comment by tibiur** [comment]
We are investigating this issue, thank you for your patience.

**Comment by kunaldas103** [comment]
Any update on this?

**Comment by tibiur** [comment]
I just checked the 5.0 example app, and it works for me. 

For the camera streaming you need the LMICoreMediaFramework. Please check the size of this framework. If there is no binary in the folder or the size of the binary is just a few bytes, there is a problem with your method getting the SDK.

Reason 1: Gitub does not include files from git-lfs in the archived file, so if you downloaded the released .zip or .tar file the binary is missing.

Reason 2: If you did not install git-lfs, git can not download the large file, so the binary is missing.

Please make sure you have git-lfs installed and use cocoapods or git clone to get the release.

You can clone version 5.0 with:
git clone https://github.com/LogmeinRescue/iOS-SDK.git --branch 5.0

Unfortunately git-lfs servers have limited bandwith, downloading from git-lfs could take a long time (cloning could can take 10-20 minutes, do not terminate the process)

**Comment by KiranKumar36** [comment]
@tibiur Yes it looks like the error is with size of binary.
Now I got download with git-lfs and it started working.

**Comment by KiranKumar36** [comment]
@tibiur Can you compress/decrease the size of LMICoreMediaFramework which is around 165MB and after compilation the end lib in binary it came as 10.4MB which we feel that is bit heavy. This can impact the size of app. Please let me know you thoughts on it.

**Comment by tibiur** [comment]
We plan to release the SDK with bitcode support around September. Hopefully this will decrease the size of the binary.
