### ISSUE TITLE
Issue in broadcast framework in archive mode

### ISSUE THREAD

**Issue by KiranKumar36** [LogmeinRescue/iOS-SDK#36]
<img width="674" alt="Screenshot 2019-05-15 at 9 41 26 AM" src="https://user-images.githubusercontent.com/29379567/57780304-f5896c80-76f5-11e9-8a87-45eea6665198.png">

**Environment**
Xcode 10.2
Swift 5
iPhone 7
iOS 12.2

**Description**
Tried to distribute the app. it fails. The issue screen shot is attached

**Comment by tibiur** [comment]
We do not support bitcode, please disable bitcode for your app.
