### ISSUE TITLE
RescueSDK 5.2: Not installing app in iOS13 devices with Xcode 11/11.1

### ISSUE THREAD

**Issue by Hari1011** [LogmeinRescue/iOS-SDK#44]
I have changed deployment target to iOS11.0 and updated RescueSDK 5.2 with Xcode 11/11.1. But I am not able to install the app in iOS13 devices, getting the error like in the attached screenshot.  In iOS 12 and below devices, camera is not working. And in RescueSDK example app also same issue. Please help me on this.

Installed RescueSDK by using CocoaPods like below
target 'MyAppTarget' do
 pod 'RescueSDK/Core'
 pod 'RescueSDK/LMICoreMedia'
end

<img width="423" alt="Screenshot 2019-11-04 at 9 15 15 PM" src="https://user-images.githubusercontent.com/9198288/68139935-01d9de00-ff51-11e9-8d80-d66dc35700d0.png">

**Comment by tibiur** [comment]
Do you have git-lfs installed? Cocoapods use git-lfs to get large files like the binary is in LMICoreMedia.framework. It should be around 165MB.

**Comment by Hari1011** [comment]
Yes tibiur, I have installed git-lfs and cocoapods downloaded LMICoreMedia.framework(165MB) file. After this process only I got this issue.

**Comment by tibiur** [comment]
Found what's the problem: the Info.plist file is missing from the LMICoreMedia.framework. 
Quick fix: restore it from the previous release.
We will restore this file and create a new release shortly.

**Comment by Hari1011** [comment]
Thank you @tibiur , It is working fine with the latest RescueSDK(5.3).
