### ISSUE TITLE
Recompile the SDK

### ISSUE THREAD

**Issue by MintBerryCrunch** [LogmeinRescue/iOS-SDK#45]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: ~/RescueSDK/Frameworks/RescueCore.framework/Modules/RescueCore.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by tibiur** [comment]
Which Xcode version do you use?

**Comment by tibiur** [comment]
we are planning to release a new version with Xcode 11.2.1 GM shortly

**Comment by SeanRobinson159** [comment]
Thanks for the update, it is now working for me in Xcode 11.2.1.
