### ISSUE TITLE
Feature Request: Add ability to disable automatic notifications

### ISSUE THREAD

**Issue by nripoli4810** [LogmeinRescue/iOS-SDK#52]
The [documentation](https://github.com/LogmeinRescue/iOS-SDK/wiki/First-Steps) shares that the SDK sends local notifications automatically. We would like to disable these notifications in favor of our own notifications.

For example, in our current flow, we display a local notification as soon as a broadcast session starts. This becomes confusing to the user once the app is backgrounded because they receive a second notification from the SDK itself. Controlling the notification ourselves also allows us to link the user back to a specific screen within our app (rather than just re-opening to the last screen when tapped).

**Comment by exceptioncatcher91** [comment]
Hi @nripoli4810,

We will look into it.

Daniel

**Comment by exceptioncatcher91** [comment]
Hi @nripoli4810,

Use SDK 5.8.1 to switch off notifications. All you have to do is to set RescueSession's 'disableNotifications' property to true, before you invoke 'startSession()'.

Daniel

**Comment by nripoli4810** [comment]
Many thanks @exceptioncatcher91.

We'll try this out in an upcoming sprint and will follow up in a new issue if we have any questions.
