### ISSUE TITLE
Documentation Request for SDK Notifications

### ISSUE THREAD

**Issue by nripoli4810** [LogmeinRescue/iOS-SDK#53]
The documentation shares that the Rescue SDK sends local notifications. The only notification that we are aware of is when a user sends the application to the background. I assume the others may be for the chat feature, but we’re not currently using that.

Could you add a list of the automatically displayed local notifications and their trigger criteria to the wiki or documentation? This will aid our designers and testers as we work on a new user flow.

Thanks!

**Comment by exceptioncatcher91** [comment]
Hi @nripoli4810,

There are two kind of notification in our SDK. You can find the documentation about them here:
https://github.com/LogmeinRescue/iOS-SDK/wiki/Chat#displaying-local-notifications-background

Daniel

**Comment by nripoli4810** [comment]
Thanks @exceptioncatcher91 for the link to the documentation!
