### ISSUE TITLE
Application stops receiving LMI status updates from agent after 2 screen share sessions

### ISSUE THREAD

**Issue by jamesdownsjr2913** [LogmeinRescue/iOS-SDK#58]
Tested in versions 5.6, 5.8.1, and 5.9. Tested using the macOS version of the LogMeIn Rescue Technician Console app.

After 2 screen share sessions, using a broadcast extension to start a RescueBroadcastSession, the client application stops receiving session state updates from the agent application. This can be reproduce as follows:

1. Start a screen broadcast and bring the state all the way to "Active"
2. End the screen broadcast
3. Start another screen broadcast and bring it to "Active"
4. End the screen broadcast
5. Start either a screen broadcast or camera share and bring it to "Active"
   - If you manually accept the "Waiting" broadcast as an agent, the client won't receive "Connected" as a state
6. End the broadcast or camera share from the agent dashboard
   - The client never receives a "Disconnecting" or "Disconnected" state

This has been verified in multiple internal apps. Our internal apps allow both broadcasting and camera sharing within the same application. I cannot verify this behavior in the example app in this repo because it does not seem to ever receive the "Connected", "Waiting", or "Idle" event. It also never seems to receive "Disconnecting" or "Disconnected" when the agent ends the session either.

Closing and re-opening the agent dashboard does not fix the issue. Force-closing the app and re-opening does fix the issue until 2 more screen share sessions are started.

Our broadcast session are set up according to the documentation in the Wiki:
https://github.com/LogmeinRescue/iOS-SDK/wiki/Broadcasting

**Comment by jamesdownsjr2913** [comment]
It looks like this is fixed as part of the changes to fix https://github.com/LogmeinRescue/iOS-SDK/issues/59 in version 5.10-beta.1

**Comment by exceptioncatcher91** [comment]
@jamesdownsjr2913 I am really happy to hear that! ;)
