### ISSUE TITLE
LogMeIn Rescue Technician Console desktop app does not relay the "disconnecting" event to the iOS SDK

### ISSUE THREAD

**Issue by jamesdownsjr2913** [LogmeinRescue/iOS-SDK#59]
Tested on 5.6, 5.8.1, and 5.9. Tested using the macOS version of the LogMeIn Rescue Technician Console app.

When the agent ends the session from the "LogMeIn Rescue Technician Console" desktop app, the disconnect events are not sent to client using the session. This has been reproduced in two internal apps and the example app in this repo. It was also noticed the example app is not relaying the "idle" status (or any status at all) that the agent causes with the desktop app. This issue may be related to issue https://github.com/LogmeinRescue/iOS-SDK/issues/58. If you'd rather consolidate them I'm fine with that.

This behavior is not consistent with the Android SDK. Events from the "LogMeIn Rescue Technician Console" desktop app are relayed to the Android SDK (when an agent ends the session, the client is made aware and gets the "disconnecting" event.

**Comment by exceptioncatcher91** [comment]
@jamesdownsjr2913 Thanks for sharing your experience. Is this reproducible with broadcast / camera session?

**Comment by jamesdownsjr2913** [comment]
I only noticed it with screen broadcast. Camera share sessions seems to get "disconnect" events from the console consistently.

**Comment by exceptioncatcher91** [comment]
@jamesdownsjr2913 Thanks, investigation in progress.

**Comment by exceptioncatcher91** [comment]
@jamesdownsjr2913 Hi, Our new release 5.10-beta.1 is now available via Cocoapods. Could you validate all of your issues?
Now, you get session status information via RescueBroadcastDelegate (func rescueBroadcastSessionStatusDidChange(_ status: RescueSessionStatus), but don't forget to set RescueSession.sharedInstance.broadcastDelegate. If you would like to end a broadcast session, please use RescueSession.sharedInstance.endBroadcastSession(). Please check our RescueBroadcastExampleExternal project for an example. If you have problems or questions, do not hesitate to contact with us.

**Comment by jamesdownsjr2913** [comment]
So far, it seems like the `func rescueBroadcastSessionStatusDidChange(_ status: RescueSessionStatus)` function is doing what we'd expect by receiving all the broadcast events. Is there any technical reason to continue using `func rescueBroadcastDidStart()` or `func rescueBroadcastDidStop()` now. They seem to be in conflict with this new function since it'd be updating on connecting/disconnecting anyway.

**Comment by exceptioncatcher91** [comment]
@jamesdownsjr2913 You should use further the rescueBroadcastDidStart and rescueBroadcastDidStop. When you get the first connected state during a session, it means that the broadcast has been started. But you can get connected state multiple times during a session, for example when you go to reconnect / onhold state, and then back to connected again. rescueBroadcastDidStart triggered only if you get into connected state, and broadcasting has not been started yet. So rescueBroadcastDidStart is not equivalent with the connected state, what you get via rescueBroadcastSessionStatusDidChange. rescueBroadcastDidStop runs only, if you broadcasted before it
