### ISSUE TITLE
Cocopods is not fetching latest version from the pods.

### ISSUE THREAD

**Issue by Abhu08** [LogmeinRescue/iOS-SDK#62]
We have been using RescueSD/Core and RescueSDK/LMICoreMedia version 5.7, it stopped working on November 10 because, the LMICoreMedia file is not available in the build file, and found it is because the file hosted in git is no more available. We decided to upgrade it to the latest version using cocoa pods and the pod is not downloading the latest version 5.10 instead, it is downloading version 5.8.1. We tried explicitly by giving the version like below, but it didn't download and reported an error
 CocoaPods **could not find compatible versions for pod "RescueSDK/Core":
 In Podfile:
  RescueSDK/Core (= 5.10) failed. Please check and let us know.**
**steps tried**
pod 'RescueSDK/Core', '5.10'
pod 'RescueSDK/LMICoreMedia', '5.10' ----- > Reported an error

**Step 2**
pod 'RescueSDK/Core'
pod 'RescueSDK/LMICoreMedia' ----- > It is downloading 5.8.1 version instead of latest version 5.10.
 
Please check and update on this. Thanks

**Comment by exceptioncatcher91** [comment]
Hi @Abhu08 

Thanks your remark. What is the value of your platform field in podfile? If you would like to use SDK 5.10, you should have `platform :ios, '12.0'` in your pod file. SDK 5.8.1 is the latest version, which is available with `platform :ios, '11.0'`. 

Daniel

**Comment by Abhu08** [comment]
Oh, Thanks. Ours is ios 11.0. But nowhere it is specified the latest version requires 12.0 which caused the confusion.

**Comment by exceptioncatcher91** [comment]
We specified it on our Wiki / Requirement page. https://github.com/LogmeinRescue/iOS-SDK/wiki/Requirements
