### ISSUE TITLE
Issue when trying to connect to a session

### ISSUE THREAD

**Issue by AvoChris** [LogmeinRescue/iOS-SDK#63]
I'm getting this error when trying to connect to a session, it doesn't matter if the pin is valid or not.

        RescueSession.sharedInstance.delegate = self
        RescueSession.sharedInstance.apiKey = API_KEY
        RescueSession.sharedInstance.connectToSessionAutomatically = false
        RescueSession.sharedInstance.appGroup = "group.com.example.example"
        RescueSession.sharedInstance.sessionStartParameters.start(withPinCode: pinCode)
        RescueSession.sharedInstance.startSession()

[Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}

Does anyone have an idea as to what can cause this issue and what can potentially fix the issue?

**Comment by exceptioncatcher91** [comment]
Hi @AvoChris,

Can you successfully connect to session? We use CoreTelephony framework in our SDK and this error message may come from it. Where did you put the code that you have attached? Is it (or part of it) in your Appdelegate's `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool `or in a view controller's `viewDidLoad()`?

Daniel

**Comment by AvoChris** [comment]
Hi @exceptioncatcher91 

So the app I'm working on is just a rebrand of a previous app that had this functionality working. I haven't changed anything with the connecting to sessions but it doesn't seem to connect at all anymore. Whether I enter a correct pin or an incorrect pin I get the above error message.

The code is being called inside a view controllers viewWillAppear() function.

**Comment by AvoChris** [comment]
Yes I have implemented the rescueSessionError, essentially just presenting and alert dialog notifying the user an error has occurred as well as printing the error rawValue. The rawValue of the error is just 12 withUserInfo being nil.

**Comment by exceptioncatcher91** [comment]
If the rawValue of the error is 12 then it means that your API key is not valid with your app's bundle id. (Value name: apiKeyAndAppIdNotFromTheSameCompany). Please check `Step Four. Generate an API key` section on this page: https://github.com/LogmeinRescue/iOS-SDK/wiki/First-Steps

**Comment by AvoChris** [comment]
Thank you so much for the assistance, that actually makes a lot of sense now.
