### ISSUE TITLE
Camera stream sent to back.

### ISSUE THREAD

**Issue by AvoChris** [LogmeinRescue/iOS-SDK#65]
Hi,

I know this isn't the correct place to post this but I've posted an issue on the Android-SDK github with no response for going on 3 days now. I have an issue with the Android SDK saying the app is being sent to back on the technician console when on the device the camera stream is the only thing visible. I can even see the camera un-blur when the session connects but the technician cannot see anything as it says the customer has sent app to background.

I'm not sure if anyone here can help me but I've been rattling my brain for days now and I've had no success. Any help would be appreciated.

**Comment by tbalogh** [comment]
Hi @AvoChris ,

Sorry for keep you waiting. I hope you don't mind, if I close the ticket and we continue the discussio [here](https://github.com/LogmeinRescue/Android-SDK/issues/46).

Best,
Tamas
