### ISSUE TITLE
RescueSDK-Broadcast Multiple commands produce ....XCFrameworkIntermediates/RescueBroadcast

### ISSUE THREAD

**Issue by mdflores** [LogmeinRescue/iOS-SDK#66]
I tried integrating the Broadcast SDK in our app with the Broadcast Upload Extension.. and we are receiving

> Multiple commands produce '/Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED-
> barlvhqutairsyczcmydolwwqyfj/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/RescueBroadcast':
> 1) That command depends on command in Target 'RescueSDK-Broadcast-Core-LMICoreMedia' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
> 2) That command depends on command in Target 'RescueSDK-Broadcast' (project 'Pods'): script phase “[CP] Copy XCFrameworks”

pod file contains:

> target 'OurTarget' do
>   use_frameworks!
>  inhibit_all_warnings!
>   pod 'RescueSDK/Core'
>   pod 'RescueSDK/LMICoreMedia'
>   pod 'RescueSDK/Broadcast'
> end
> 
> target 'RemoteSharingExtension' do  
>   use_frameworks!
>   pod 'RescueSDK/Broadcast'
> end

Need help on this, we just integrated straight forward 

Build System: 
Xcode 12.3
Swift 5
Cocoapods 1.10.1
Minimum iOS 12

**Comment by exceptioncatcher91** [comment]
Hi @mdflores,

Thanks for your remark. I think, this might be an issue with Cocoapods: https://github.com/CocoaPods/CocoaPods/issues/10106
Would you like to use our latest RescueSDK pod (5.10)?
Have you already compiled our Example projects (https://github.com/LogmeinRescue/iOS-SDK/tree/master/Examples)?

Daniel

**Comment by mdflores** [comment]
Yes I tried it also integrating it with pods and it has the same issue.. I somehow manage to compile it. Its the "New Build System" of Xcode.. I switched back to the "Legacy Build System" and it worked. I think this is only a temporary fix since the Legacy Build System will be deprecated in the future..

Closing this issue for now.
