### ISSUE TITLE
BitCode Support

### ISSUE THREAD

**Issue by mdflores** [LogmeinRescue/iOS-SDK#67]
We are trying to create an Archive for our app that integrates LogmeinRescue. our project is bitcode enabled. Xcode is failing the archiving process. Is there a way to support this?

> ld: bitcode bundle could not be generated because '/Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED-barlvhqutairsyczcmydolwwqyfj/Build/Intermediates.noindex/ArchiveIntermediates/REDACTED/BuildProductsPath/UAT-iphoneos/XCFrameworkIntermediates/RescueBroadcast/RescueBroadcast.framework/RescueBroadcast' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED-barlvhqutairsyczcmydolwwqyfj/Build/Intermediates.noindex/ArchiveIntermediates/REDACTED/BuildProductsPath/UAT-iphoneos/XCFrameworkIntermediates/RescueBroadcast/RescueBroadcast.framework/RescueBroadcast' for architecture arm64

Xcode: 12.3
Swift 5
Bitcode Enabled

Thanks!

**Comment by exceptioncatcher91** [comment]
Hi @mdflores 

Thanks for reporting this issue. Our new sdk release (5.11) is going to contain this fix.

Daniel

**Comment by exceptioncatcher91** [comment]
@mdflores Our new SDK version (5.11) has been released and available via Cocoapods.

**Comment by mdflores** [comment]
Thank you will try and update to the latest one..
