### ISSUE TITLE
Rescue Broadcast Not Working on iOS 14.

### ISSUE THREAD

**Issue by mdflores** [LogmeinRescue/iOS-SDK#70]
Hi, we were using the RescueSDK 5.10 and its not working with iOS 14.. But it works perfectly on iOS 13. So to isolate the issue we used your sample app and its the same case. We also tried [Rescue +](https://apps.apple.com/us/app/rescue-mobile/id661269562) from AppStore and its also not working on iOS 14.

[Video Recording](https://drive.google.com/file/d/1mUw5V9pGQzPJN4VS_oJL0tLLUIfp6_IN/view?usp=sharing)

Test Devices on Rescue + App:
iPhone XS MAX iOS 14.8
iPhone 8 Plus iOS 13.3.1

Rescue + App 7.3.1

Test Devices on Sample App:
iPhone XS MAX iOS 14.8
iPhone 8 Plus iOS 13.3.1

RescueSDK 5.10
Xcode 12.5.1

**Comment by mdflores** [comment]
Any updates on this?

**Comment by exceptioncatcher91** [comment]
Hi @mdflores 

Unfortunately, we could not reproduce this issue. My tips is that the broadcast extension crashes, but I do not know why. I attached the broadcast extension process into Xcode, and the memory usage was below the limit (50MB). Could you attach the broadcast process into the Xcode and check the memory level? 

Thanks, Daniel

**Comment by mdflores** [comment]
@exceptioncatcher91 The same happens on the Rescue + app found in the video.. We will gather more info about this.

**Comment by mdflores** [comment]
@exceptioncatcher91 we have upgraded to 5.12 and its working now as expected.
