### ISSUE TITLE
Implicit bluetooth permission is not silent

### ISSUE THREAD

**Issue by jamesdownsjr2913** [LogmeinRescue/iOS-SDK#72]
Testing device: iPhone 11 on iOS 14.5
LMI SDK version: 5.11

According to the documentation, the user should not see a bluetooth permission prompt in the consuming application (https://github.com/LogmeinRescue/iOS-SDK/wiki/Requirements):
> Include the NSBluetoothPeripheralUsageDescription key in your app's Info.plist file and provide a purpose string for this key. The SDK, however, does not use the Bluetooth device, it just queries the device state. So, this message will never be displayed to your user

Despite this, the bluetooth permission prompt is shown in the consuming application, including this string given in the usage description.

Is this behavior a bug, a change in OS behavior since this documentation has been written, or an implementation detail we need more clarity on to implement correctly? We currently have both **NSBluetoothAlwaysUsageDescription** and **NSBluetoothPeripheralUsageDescription** but the latter seems to not be relevant to the LMI SDK. We do not directly use CoreBluetooth and only the LMI SDK is implicitly requiring this permission in our application.

If this is expected, can further detail be given as to why the bluetooth permission is needed by LMI so that we can give a better explanation to our end users via the prompt? (See https://github.com/LogmeinRescue/iOS-SDK/issues/74)

**Comment by exceptioncatcher91** [comment]
Hi @jamesdownsjr2913,

Ww have updated our documentation's requirements page. https://github.com/LogmeinRescue/iOS-SDK/wiki/Requirements

Thanks for your remark!

**Comment by jamesdownsjr2913** [comment]
Thanks for the update. The new documentation seems to sufficiently explain these questions. I'll mark this as closed.
