### ISSUE TITLE
Provide clarity surrounding the usage of bluetooth by LMI

### ISSUE THREAD

**Issue by jamesdownsjr2913** [LogmeinRescue/iOS-SDK#74]
Testing device: iPhone 11 on iOS 14.5
LMI SDK version: 5.11

According to the documentation, bluetooth is used by the SDK to query state and pass that information to an agent (https://github.com/LogmeinRescue/iOS-SDK/wiki/Requirements):
> The SDK links Apple CoreBluetooth framework to send information about the device

1. What information exactly is being sent with this information? Is it critical or just additional tangential information that an LMI agent could acquire verbally if necessary?
2. Is the **NSBluetoothPeripheralUsageDescription** key needed as well for any reason?

This information is needed to provide documentation around why a user is being prompted for this permissions and create the usage description string for users to see (see https://github.com/LogmeinRescue/iOS-SDK/issues/72 that the permission is not silent)

**Comment by exceptioncatcher91** [comment]
Hi @jamesdownsjr2913,

We send the state of the Bluetooth (switched on/off) to the agent. Currently there is no opportunity to switch this feature off, so the user will be prompted for Bluetooth permission.

NSBluetoothPeripheralUsageDescription info.plist key is necessary below iOS 13:
https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothperipheralusagedescription?language=objc
If your application deployment target is iOS 13 or higher, than i think NSBluetoothAlwaysUsageDescription should be enough for you.

We are going to update our the documentation, thanks for your remarks.

**Comment by jamesdownsjr2913** [comment]
Thanks for clarifying the use case of the bluetooth permissions and the documentation updates. This seems to cover my questions above so I will mark this as closed.
