### ISSUE TITLE
Swift Package Manager Distribution Support

### ISSUE THREAD

**Issue by jamesdownsjr2913** [LogmeinRescue/iOS-SDK#78]
Binary targets can be distributed as Swift packages as long as each binary target is distributed individually. Per Apple's documentation here:
https://developer.apple.com/documentation/PackageDescription/Target/binaryTarget(name:url:checksum:)

> url: The URL to the binary artifact. This URL must point to an archive file that contains a binary artifact in its root directory.

From there, to be able to distribute as a Swift Package, there is some work that needs to be done for RescueSDK. This work is similar to the work Salesforce and Dext did to distribute the ServiceSDK frameworks in a Swift Package:
https://github.com/Salesforce-Async-Messaging/Swift-Package-ServiceChat
https://github.com/dext/SalesforceServiceSDK-iOS

If this work was done we'd be able to consume the RescueSDK with Swift Package Manager, allowing us to switch from Cocoapods for our dependency management, enabling better support for new and upcoming features like Xcode Cloud

If this work is out of scope for the project now, the minimum short-term request would be to at least split the xcframeworks into separate zip files when distributing. This would allow us to internally build our own Swift Package for RescueSDK and consume it without having to manage the xcframeworks ourselves.

Related PR for example purposes: https://github.com/LogmeinRescue/iOS-SDK/pull/79

**Comment by exceptioncatcher91** [comment]
Hi @jamesdownsjr2913,

Now you can use our master branch with SPM.

Daniel
