### ISSUE TITLE
Camera Share view distortion

### ISSUE THREAD

**Issue by campbell-jake** [LogmeinRescue/iOS-SDK#81]
We observe distortion of content in the user's camera view. This was reproduced, to a lesser extent, in the native rescue lens app. The distortion presents as slight vertical elongation of the object in view of the camera on the user device. It is not distorted in the agent dashboard. 

In our own consuming application, we attempted a workaround in which we cropped/resized the view to remove the distortion. But doing so caused agent annotations to appear displaced in the wrong location. So it is not a viable, long-term solution.

Recommendation on what to do, or is this a bug that needs to be addressed?
Attached images demonstrate the view distortion/elongation present in the user camera preview.
<img width="308" alt="User Camera" src="https://user-images.githubusercontent.com/62573745/221896391-3d502e27-7925-48c7-b0b9-eac10159c483.png">
<img width="308" alt="Agent Dashboard" src="https://user-images.githubusercontent.com/62573745/221896440-39ce98d3-2e4f-492a-ad19-ccc8697fd626.png">

**Comment by tamastimar** [comment]
Hi @campbell-jake, thanks for the report. We'll look into it soon.

**Comment by campbell-jake** [comment]
@tamastimar To follow up- could you provide an estimate as to an investigation timeline?

**Comment by exceptioncatcher91** [comment]
Hi @campbell-jake,

This bug has been fixed in SDK v5.15.

Daniel
