### ISSUE TITLE
ios version 15.1 connection issues

### ISSUE THREAD

**Issue by ncoussens222** [LogmeinRescue/iOS-SDK#86]
I'm currently encountering issues when trying to initiate a remote camera share session. My iOS device appears to enter a connected state (camera share will start on the device), but on the technician console the camera share screen will never show up. From there, trying to set the stream to pause or resume from my device appears to not change anything on the technician console, and will cause unexpected behavior on my device (the camera share screen will go blurry). Are there any known issues like this for this version of iOS?

**Comment by exceptioncatcher91** [comment]
Hi @ncoussens222 ,

Could you tell me please what are the version numbers of the technician console and the SDK? Are you using the technician console from Mac or Windows?

**Comment by ncoussens222** [comment]
Hi @exceptioncatcher91 ,
Thanks for following up on this. Unfortunately, I've since moved off of this iOS version, and will be unable to do any future verification for the behavior I was seeing. As such, you can feel free to close this issue.
The technician console version was: 7.12.3334.13-1.0.69 (1.0.69) from Mac
The SDK version I was using was: 5.15
