### ISSUE TITLE
Swift Package Manager requires tags to follow semantic versioning to declare by tag

### ISSUE THREAD

**Issue by jamesdownsjr2913** [LogmeinRescue/iOS-SDK#91]
When trying to declare the LogMeIn Rescue SDK in a Package.swift file for Swift Package Manager, the tag/version is unable to be used because it does not follow semantic versioning. Example of Package.swift:

```
// swift-tools-version:5.9
import PackageDescription

let package = Package(
  name: "ExamplePackage",
  dependencies: [
    .package(url: "https://github.com/LogmeinRescue/iOS-SDK.git", exact: "5.17")
...
```

The above package would result in the following error when describing the Package file.

> Invalid semantic version string '5.17'
> error: fatalError

Swift Package Manager would require a patch version be provided (e.g. 5.17.0) on the tag to be able to pull it. As it is now, the only way to pull tags would be to use the commit hash.

EDIT: It looks like Xcode may be able to resolve this itself by just assuming a patch of "5.17.0". Running swift on the command line may behave the same but the consumer has to know to add .0 as the patch version. This may work as a work around but is not tested.

**Comment by exceptioncatcher91** [comment]
@jamesdownsjr2913  Thanks for reporting this issue. We are not going to change the version format of the SDK in the near future, so please use the workaround (add .0 as a patch version).
